version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run: 
          name: install pip
          command: pip install -U pip setuptools wheel
      - run:
          name: requirements
          command: pip install -r etc/requirements.txt
      - run:
          name: static type checks
          command: mypy --config-file etc/mypy.ini src
      - run:
          name: formatting
          command: black -t py38 --check src/ tests/
      - run:
          name: tests
          command: pytest